export enum BotState {
    IDLE = 'IDLE',

    SELECT_COMPLEX = 'SELECT_COMPLEX',

    SELECT_RESOURCE = 'SELECT_RESOURCE',

    SELECT_BUILDING = 'SELECT_BUILDING',

    SELECT_SECTION = 'SELECT_SECTION',

    INPUT_READING = 'INPUT_READING',
    INPUT_SERIAL_NUMBER = 'INPUT_SERIAL_NUMBER',
    CONFIRM_SERIAL_OCR = 'CONFIRM_SERIAL_OCR',
    REVIEW_SERIAL_METER = 'REVIEW_SERIAL_METER',
    INPUT_HEAT_SERIAL = 'INPUT_HEAT_SERIAL',
    CONFIRM_HEAT_SERIAL = 'CONFIRM_HEAT_SERIAL',

    REVIEW_SELF_READING = 'REVIEW_SELF_READING',

    CONFIRM_READING = 'CONFIRM_READING',
}
