export enum BotState {
    IDLE = 'IDLE',

    SELECT_COMPLEX = 'SELECT_COMPLEX',

    SELECT_RESOURCE = 'SELECT_RESOURCE',

    SELECT_BUILDING = 'SELECT_BUILDING',

    SELECT_SECTION = 'SELECT_SECTION',

    INPUT_READING = 'INPUT_READING',
    INPUT_SERIAL_APARTMENT = 'INPUT_SERIAL_APARTMENT',

    REVIEW_SELF_READING = 'REVIEW_SELF_READING',

    CONFIRM_READING = 'CONFIRM_READING',
}
