export enum BotState {
    IDLE = 'IDLE',

    SELECT_RESOURCE = 'SELECT_RESOURCE',

    SELECT_BUILDING = 'SELECT_BUILDING',

    SELECT_SECTION = 'SELECT_SECTION',

    INPUT_READING = 'INPUT_READING',

    CONFIRM_READING = 'CONFIRM_READING',
}
